require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/create_owners", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CreateOwner. As you add validations to CreateOwner, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CreateOwner.create! valid_attributes
      get create_owners_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      create_owner = CreateOwner.create! valid_attributes
      get create_owner_url(create_owner)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_create_owner_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      create_owner = CreateOwner.create! valid_attributes
      get edit_create_owner_url(create_owner)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CreateOwner" do
        expect {
          post create_owners_url, params: { create_owner: valid_attributes }
        }.to change(CreateOwner, :count).by(1)
      end

      it "redirects to the created create_owner" do
        post create_owners_url, params: { create_owner: valid_attributes }
        expect(response).to redirect_to(create_owner_url(CreateOwner.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CreateOwner" do
        expect {
          post create_owners_url, params: { create_owner: invalid_attributes }
        }.to change(CreateOwner, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post create_owners_url, params: { create_owner: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested create_owner" do
        create_owner = CreateOwner.create! valid_attributes
        patch create_owner_url(create_owner), params: { create_owner: new_attributes }
        create_owner.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the create_owner" do
        create_owner = CreateOwner.create! valid_attributes
        patch create_owner_url(create_owner), params: { create_owner: new_attributes }
        create_owner.reload
        expect(response).to redirect_to(create_owner_url(create_owner))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        create_owner = CreateOwner.create! valid_attributes
        patch create_owner_url(create_owner), params: { create_owner: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested create_owner" do
      create_owner = CreateOwner.create! valid_attributes
      expect {
        delete create_owner_url(create_owner)
      }.to change(CreateOwner, :count).by(-1)
    end

    it "redirects to the create_owners list" do
      create_owner = CreateOwner.create! valid_attributes
      delete create_owner_url(create_owner)
      expect(response).to redirect_to(create_owners_url)
    end
  end
end
